[package]
name = "bson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = { version = "2.3.0" }
serde = { version = "1.0.145", features = ["derive"] }

